import type {Localization} from './localization'

export const localizationEn: Localization = {
  financingAccounting: 'Financing accounting',
  switchToEnglish: 'Switch to English',
  switchToRussian: 'Switch to Russian',
  login: 'Login',
  email: 'Email',
  password: 'Password',
  logIn: 'Log in',
  registration: 'Registration',
  signUp: 'Sign up',
  dontHaveAnAccountQuestion: 'Don`t have an account?',
  alreadyHaveAnAccountQuestion: 'Already have an account?',
  incorrectEmailAddress: 'Incorrect email address',
  fieldIsRequired: 'Field is required',
  minimumPasswordLength: 'Minimum password length is {} characters',
  expenses: 'Expenses',
  categories: 'Categories',
  reports: 'Reports',
  comment: 'Comment',
  create: 'Create',
  edit: 'Edit',
  delete: 'Delete',
  amount: 'Amount',
  date: 'Date',
  category: 'Category',
  showMore: 'Show more',
  noSpending: 'No spending',
}
