import type {Localization} from './localization'

export const localizationRu: Localization = {
  financingAccounting: 'Учет финансов',
  switchToEnglish: 'Переключить на английский',
  switchToRussian: 'Переключить на русский',
  login: 'Вход',
  email: 'Электронная почта',
  password: 'Пароль',
  logIn: 'Войти',
  registration: 'Регистрация',
  signUp: 'Зарегистрироваться',
  dontHaveAnAccountQuestion: 'Нет аккаунта?',
  alreadyHaveAnAccountQuestion: 'Уже есть аккаунт?',
  incorrectEmailAddress: 'Неверный формат email',
  fieldIsRequired: 'Поле не должно быть пустым',
  minimumPasswordLength: 'Минимальная длина пароля - {} символов',
  expenses: 'Расходы',
  categories: 'Категории',
  reports: 'Отчеты',
  comment: 'Комментарий',
  create: 'Создать',
  edit: 'Редактировать',
  delete: 'Удалить',
  amount: 'Сумма',
  date: 'Дата',
  category: 'Категория',
  showMore: 'Показать еще',
  noSpending: 'Нет трат',
  eng: 'Англ',
  rus: 'Рус',
}
